version: '3.9'

x-php-image:
  &php-image
  build:
    dockerfile: scripts/docker/Dockerfile
  image: cycletime/worker:1.0.4-xdebug
  init: true
  networks:
    - php
    - redis
    - database
  volumes:
    - '~/.composer:/tmp:delegated'
    - './:/var/www/html:delegated'

x-pgsql-image:
  &pgsql-image
  environment:
    - 'POSTGRES_DB=${DB_DATABASE}'
    - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    - 'POSTGRES_USER=${DB_USERNAME}'
  image: 'postgres:15.0-alpine'
  init: true
  networks:
    - database

x-node:
  &node-template
  image: node:18-slim
  init: true
  user: node
  environment:
    - NODE_ENV=development
  volumes:
    - "~/.npm:/usr/local/npm:delegated"
    - "./:/home/node/app:delegated"
  working_dir: "/home/node/app"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:1.0.1-alpine
    networks:
      - external
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx:
    image: 'nginx:1.23.1-alpine'
    init: true
    depends_on:
      - nginx-proxy
    networks:
      - external
      - php
    ports:
      - '8080:80'
    restart: on-failure
    volumes:
      - './:/var/www/html:cached'
      - './scripts/nginx/conf.d/:/etc/nginx/conf.d/:cached'
    environment:
      - 'VIRTUAL_HOST=cycletime.test'

  pgsql:
    <<: *pgsql-image
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'

  pgsql-testing:
    <<: *pgsql-image

  php:
    <<: *php-image
    environment:
      - 'COMPARE_ENV_FILES=${COMPARE_ENV_FILES:-0}'
      - 'PHP_IDE_CONFIG=${PHP_IDE_CONFIG}'

  worker:
    <<: *php-image
    command: [ "php", "artisan", "queue:work" ]
    restart: unless-stopped

  node:
    <<: *node-template
    ports:
      - "5173:5173"
    command: "npm run dev"

  redis:
    image: 'redis:7.0.4-alpine'
    init: true
    networks:
      - php
      - redis
networks:
  database:
  php:
  redis:
  external:
volumes:
  db-data:
