version: '3.9'

x-php-image:
  &php-image
  build:
    dockerfile: scripts/docker/Dockerfile
  image: cycletime/worker:1.0.3
  init: true
  networks:
    - php
    - redis
    - database
  volumes:
    - '~/.composer:/tmp:delegated'
    - './:/var/www/html:delegated'

x-pgsql-image:
  &pgsql-image
  environment:
    - 'POSTGRES_DB=${DB_DATABASE}'
    - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    - 'POSTGRES_USER=${DB_USERNAME}'
  image: 'postgres:15.0-alpine'
  init: true
  networks:
    - database

services:
  pgsql:
    <<: *pgsql-image
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'

  pgsql-testing:
    <<: *pgsql-image

  php:
    <<: *php-image
    environment:
      - 'COMPARE_ENV_FILES=${COMPARE_ENV_FILES:-0}'
      - 'PHP_IDE_CONFIG=${PHP_IDE_CONFIG}'

  worker:
    <<: *php-image
    command: [ "php", "artisan", "queue:work" ]
    restart: unless-stopped

  redis:
    image: 'redis:7.0.4-alpine'
    init: true
    networks:
      - php
      - redis
networks:
  database:
  php:
  redis:
volumes:
  db-data:
