name: 'Main deploy'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    tests:
        name: PHP Tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: php-actions/composer@v5 # or alternative dependency management
            -   name: PHPUnit Tests
                uses: php-actions/phpunit@v3
                with:
                    bootstrap: vendor/autoload.php
                    configuration: phpunit.xml
                    args: --coverage-text
                    php_extensions: xdebug calendar
                env:
                    XDEBUG_MODE: coverage

