name: 'Main deploy'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    lint:
        name: Lint PHP Code
        runs-on: ubuntu-22.04
        steps:
            -   name: Setup PHP with tools
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
                    tools: phpunit
                    coverage: xdebug

