name: 'Main deploy'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    tests:
        name: PHP Tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Cache Composer dependencies
                uses: actions/cache@v2
                with:
                    path: /tmp/composer-cache
                    key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            -   name: Install Dependencies
                uses: php-actions/composer@v6
                with:
                    php_extensions: calendar

            -   name: PHPUnit Tests
                uses: php-actions/phpunit@v3
                with:
                    bootstrap: vendor/autoload.php
                    configuration: phpunit.xml
                    args: --coverage-text
                    php_extensions: xdebug calendar
                env:
                    XDEBUG_MODE: coverage

